INTERSTELLAR_SERVER_ENABLED = True
INTERSTELLAR_SERVER_HOST = '0.0.0.0'
INTERSTELLAR_SERVER_PORT = None
INTERSTELLAR_SERVER_PORT_DELTA = 1000

# needs to be something like "{service_name}.{server_class}"
INTERSTELLAR_SERVERS = []

INTERSTELLAR_SERVER_METADATA_USER = "request_user"
INTERSTELLAR_SERVER_METADATA_SERVICE = "request_service"
